[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
rustflags = [
    "-C", "relocation-model=static",
    "-C", "code-model=kernel",
    "-C", "force-frame-pointers=yes",
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-Tlinker.ld",
]